version: '3.7'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    expose: 
      - 8000
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
